[package]
name = "localsearch"
version = "0.1.0"
authors = ["Martin Kav√≠k <martin@kavik.cz>"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
fst = { version = "0.4.0" }
utf8-ranges = "1.0.4"
num-traits = "0.2.12"
